env:
  #TERM vars
  #
  TERM: xterm-256color

window:
  dimensions:
    columns: 100
    lines: 100
  padding:
    x: 7
    y: 6

background_opacity: 0.80

title: Alacritty

scrolling:
  history: 50
  multiplier: 2

tabspaces: 2

font:
  size: 10
  family: Hack 

colors:
  primary:
    background: '0x031221'
    foreground: '0xffffff'

bold: '0xe67cdb'
